Repository wecode-bootcamp-korea/19-1st-KLUSH-backend, pull requests merged in 2021-04, with the labels that each got.

#1 [KLUSH 이병재] add: users, products, orders, ratings app 추가 및 models.py 작성
  .gitignore
  klush/settings.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  ratings/__init__.py
  ratings/admin.py
  ratings/apps.py
  ratings/migrations/0001_initial.py
  ratings/migrations/__init__.py
  ratings/models.py
  ratings/tests.py
  ratings/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 [KLUSH 이병재]add: README.md
  README.md
Labels: Status: 리뷰 요청

#5 [KLUSH 19기 이병재]fix: orders app models 수정
  .gitignore
  orders/models.py
Labels: Status: 리뷰 요청

#3 [KLUSH 19기 황수민] Add : 회원가입 엔드포인트
  klush/urls.py
  orders/migrations/0003_auto_20210416_1326.py
  products/migrations/0002_auto_20210416_1326.py
  ratings/migrations/0002_alter_rate_rate.py
  users/migrations/0002_auto_20210416_1325.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#4 [19기 김현영]Add: 메인 페이지 메뉴바 엔드포인트 구현
  klush/urls.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#8 [KLUSH 19기 이병재] Refactor: users, products app models 수정
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
  orders/migrations/0003_auto_20210416_1326.py
  orders/models.py
  orders/views.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20210416_1326.py
  products/models.py
  products/views.py
  ratings/migrations/0001_initial.py
  ratings/migrations/0002_alter_rate_rate.py
  ratings/views.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210416_1325.py
  users/models.py
Labels: Status: 리뷰 요청

#6 [KLUSH 19기 황수민] Refactor : signin account_name 추가
  orders/migrations/0001_initial.py
  requirements.txt
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#10 [KLUSH 19기 이병재] Refactor: products app models 수정
  products/models.py
Labels: Status: 리뷰 요청

#7 [KLUSH 19기 황수민] Refactor: signup account_name 추가
  users/migrations/0002_remove_user_account_name.py
  users/models.py
  users/utils.py
  users/views.py
Labels: Status: Accepted

#11 [KLUSH 19기 이병재] Refactor: ratings app models 수정, migration 갱신
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
  products/migrations/0001_initial.py
  ratings/migrations/0001_initial.py
  ratings/models.py
  users/migrations/0001_initial.py
  users/migrations/0002_remove_user_account_name.py
Labels: Status: 리뷰 요청

#12 [19기 김현영]Refactor:메뉴 데이터 전달 엔드포인트 로직 수정
  products/views.py
Labels: Status: 리뷰 요청

#13 [19기 김현영]Add:메인 페이지 상품 리스트 데이터 전달 엔드포인트 구현
  products/urls.py
  products/views.py
Labels: Status: Conflict 발생, Status: 수정 요청

#14 [KLUSH 19기 이병재] fix: conflict clear
  products/urls.py
  products/views.py
Labels: Status: Accepted

#15 [KLUSH 19기 황수민]Add: orders 엔드포인트 POST, GET, DELETE 구현
  klush/urls.py
  orders/urls.py
  orders/views.py
Labels: Status: 리뷰 요청

#17 [KLUSH 19기 이병재] Add: rate API 추가
  klush/urls.py
  products/views.py
  ratings/urls.py
  ratings/views.py
Labels: Status: 리뷰 요청

#16 [19기 김현영]Add:상품 페이지 카테고리 별 상품 데이터 전달 엔드포인트 구현
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#18 [KLUSH 19기 황수민] Refactor: signup 회원가입 시 장바구니 생성 -> 생성하지 않도록 로직 변경(orders/views.py 에서 처리)
  users/views.py
Labels: Status: Accepted

#20 [KLUSH 19기 이병재] Refactor: products app View 수정
  products/views.py
Labels: Status: 리뷰 요청

#22 [KLUSH 19기 이병재] Refactor: ratings app view 수정
  ratings/views.py
Labels: Status: Accepted

#23 [KLUSH 19기 황수민] Add: ratings CommentView 엔드포인트
  ratings/urls.py
  ratings/views.py
Labels: Status: 리뷰 요청

#21 [KLUSH 19기 김현영]Refactor:Pagination 로직 수정
  products/views.py
Labels: Status: 리뷰 요청

#25 [KLUSH 19기 이병재] Refactor: orders app models 수정
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
  orders/models.py
  products/migrations/0001_initial.py
  ratings/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: Accepted

#19 [KLUSH 19기 황수민] Refactor: orders POST refactor
  orders/views.py
Labels: Status: Accepted

#24 [KLUSH 19기 이병재] Refactor : RateView response message 변경
  orders/views.py
  ratings/views.py
Labels: Status: Accepted

#28 [KLUSH 19기 황수민] Refactor: CommentView POST, DELETE 수정 json.JsonDecodeError로 변경
  ratings/views.py
Labels: Status: Accepted

#29 [KLUSH 19기 황수민] Refactor: signup utils.py 비밀번호 정규표현식 수정
  users/utils.py
Labels: Status: Accepted

#30 [KLUSH 19기 황수민] Refactor: order CartView GET 상품 가격 추가
  orders/views.py
Labels: Status: 리뷰 요청

#31 [KLUSH 19기 황수민]Refactor: CommentView GET 유저 아이디 추가
  ratings/views.py
Labels: Status: 리뷰 요청

#26 [KLUSH 19기 김현영]Refactor:수정 요청 반영하여 CategoryView에 병합
  products/views.py
Labels: Status: Accepted
